set dele on
set safe off
use actusuba
zap
use balances
zap
use clientes
zap
use compingr
zap
use ingrmedi
zap
use cpinsuba
zap
use ingrsuba
zap
use cpsasuba
zap
use salisuba
zap
use inicsuba
zap
use gruptera
zap
use laborato
zap
use pdsismed
zap
use medinaci
zap
use maesmedi
zap
use medinoat
zap
use movivent
zap
use compsali
zap
use salimedi
zap
use usuarios
zap
use proveedo
zap
use recetas
zap
use detarece
zap
use reembsis
zap
use rembsani
zap
use tipomedi
zap
use tiporece
zap
use tpcpingr
zap
use tpcpsali
zap
use tprcnoat
zap













use actusuba
appe from ..\datos1\actusuba
use balances
appe from ..\datos1\balances
use clientes
appe from ..\datos1\clientes
use compingr
appe from ..\datos1\compingr
use ingrmedi
appe from ..\datos1\ingrmedi
use cpinsuba
appe from ..\datos1\cpinsuba
use ingrsuba
appe from ..\datos1\ingrsuba
use cpsasuba
appe from ..\datos1\cpsasuba
use salisuba
appe from ..\datos1\salisuba
use inicsuba
appe from ..\datos1\inicsuba
use gruptera
appe from ..\datos1\gruptera
use laborato
appe from ..\datos1\laborato
use pdsismed
appe from ..\datos1\pdsismed
use medinaci
appe from ..\datos1\medinaci
use maesmedi
appe from ..\datos1\maesmedi
use medinoat
appe from ..\datos1\medinoat
use movivent
appe from ..\datos1\movivent
use compsali
appe from ..\datos1\compsali
use salimedi
appe from ..\datos1\salimedi
use usuarios
appe from ..\datos1\usuarios
use proveedo
appe from ..\datos1\proveedo
use recetas
appe from ..\datos1\recetas
use detarece
appe from ..\datos1\detarece
use reembsis
appe from ..\datos1\reembsis
use rembsani
appe from ..\datos1\rembsani
use tipomedi
appe from ..\datos1\tipomedi
use tiporece
appe from ..\datos1\tiporece
use tpcpingr
appe from ..\datos1\tpcpingr
use tpcpsali
appe from ..\datos1\tpcpsali
use tprcnoat
appe from ..\datos1\tprcnoat