USE ..\..\FACTURAR\MEDICTDO
COD="1.A0201"
SUM ALL CANTID1 TO A1 FOR MEDICINA1=COD AND ESTADO!="A"
SUM ALL CANTID2 TO A2 FOR MEDICINA2=COD AND ESTADO!="A"
SUM ALL CANTID3 TO A3 FOR MEDICINA3=COD AND ESTADO!="A"
SUM ALL CANTID4 TO A4 FOR MEDICINA4=COD AND ESTADO!="A"
SUM ALL CANTID5 TO A5 FOR MEDICINA5=COD AND ESTADO!="A"
SUM ALL CANTID6 TO A6 FOR MEDICINA6=COD AND ESTADO!="A"
SUM ALL CANTID7 TO A7 FOR MEDICINA7=COD AND ESTADO!="A"
SUM ALL CANTID8 TO A8 FOR MEDICINA8=COD AND ESTADO!="A"
SUM ALL CANTID9 TO A9 FOR MEDICINA9=COD AND ESTADO!="A"
SUM ALL CANTID10 TO A10 FOR MEDICINA10=COD AND ESTADO!="A"
?A1+A2+A3+A4+A5+A6+A7+A8+A9+A10